[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
requires-python = ">=3.13"
name = "quicksocket"
version = "0.0.3"

dependencies = [
  "dill"
]

